#!/usr/bin/env python
# encoding: utf-8
"""
t3get

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""
from t3tools import T3Tools
import sys

help_message = '''
Download a file from the Tier 3 storage element.
Author: Morten Dam Jørgensen, 2011

Examples:

  t3get /user/username/rootfile.root myrootfile.root



Installation:

  You must have your usercert.pem and userkey.pem in the ~/.globus/ folder.
  
'''


def main(argv=None):

	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return
	wd = T3Tools()
	if len(sys.argv) == 2: sys.argv.append(".") # If no output file is given, assume the same name as the input file, and place it it the current directory.
	if sys.argv[1][0] == "/":
		fromf = sys.argv[1]
	else:
		fromf = "/" + sys.argv[1]
		
		
	s = wd.t3get(fromf, sys.argv[2])
	if len(s) > 0:
	    print s
		


if __name__ == "__main__":
	sys.exit(main())
