#!/usr/bin/env python
# encoding: utf-8
"""

    t3ls (List files on the KU/Steno Tier 3 storage element)

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

from t3tools import T3Tools
import sys

help_message = '''
List folders on the Tier 3 storage element.
Author: Morten Dam Jørgensen, 2011.

Flags: 

    -l :    Print date modified, file size and filenames (default)
    -x :    Print SFrame XML input lines
    -f :    Print full path
    -r :    Print xroot path

Examples:
  t3ls /user/username
  t3ls -f /user/
'''


def main(argv=None):

    tools = T3Tools()
    if len(sys.argv) < 2 or "-h" in sys.argv:
      print help_message
      print tools.help_message
      return
      
      
    dire = "" 
    tools.flags = u""
    for i in sys.argv[1:]:
      if i[0] == "-":
          tools.flags += i[1:]
      if i[0] == "/":
          dire = i
      else:
          dire = "/" + i
      tools.t3ls(dire)

if __name__ == "__main__":
	sys.exit(main())
