#!/usr/bin/env python
# encoding: utf-8
"""
untitled.py

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

from t3tools import T3Tools
import sys

help_message = '''
Create a new folder on the storage element.
Author: Morten Dam Jørgensen, 2011.


Examples:

	Create one folder on the storage element
	t3mkdir /user/username/new_folder
	
	Create multiple folders on the storage element
	t3mkdir /user/username/new_folder /user/username/another_folder /user/folderx

'''

def main(argv=None):
	
	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return
		
	wd =  T3Tools()	
	dire = ""	
	for i in sys.argv[1:]:
		if i[0] == "/":
			dire = i
		else:
			dire = "/" + i
		s = wd.t3mkdir(dire)
		if len(s) > 0:
		    print s


if __name__ == "__main__":
	sys.exit(main())
