#!/usr/bin/env python
# encoding: utf-8
"""
untitled.py

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

import sys

from t3tools import T3Tools

help_message = '''
Move a file on the Tier 3 storage element.
Author: Morten Dam Jørgensen, 2011

Examples:

  t3mv /user/username/rootfile.root /user/username/myrootfile.root

  
'''

def main(argv=None):

	wd = T3Tools()

	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return
		
	
	dire = ""

	if sys.argv[2][0] == "/":
		dire = sys.argv[2]
	else:
		dire = "/" + sys.argv[2]

	if sys.argv[1][0] == "/":
		fromf = sys.argv[1]
	else:
		fromf = "/" + sys.argv[1]
		
	s =  wd.t3mv(fromf, dire)
	if len(s) > 0:
	    print s
		

if __name__ == "__main__":
	sys.exit(main())
