#!/usr/bin/env python
# encoding: utf-8
"""
untitled.py

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

BASE_URL = "https://ftp1.ndgf.org:2881/atlas/disk/atlaslocalgroupdisk/dk%s"
BASE_URL_STR = "https://ftp1.ndgf.org:2881/atlas/disk/atlaslocalgroupdisk/dk"

from t3tools import T3Tools
import sys

help_message = '''
Upload file(s) to the Tier 3 storage element.
Author: Morten Dam Jørgensen, 2011

Examples:

	Upload a file with a new name:
	t3cp rootfile.root /user/username/myrootfile.root
	
	Upload multiple files to a folder (the file names will not change)
	t3cp demofile.txt demofile1.txt demofile2.txt /user/username/
	t3cp *.root /user/username/folder/
	
'''

def main(argv=None):

	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return
		
	wd = T3Tools()

	dire = ""

	if sys.argv[-1][0] == "/":
		dire = sys.argv[-1]
	else:
		dire = "/" + sys.argv[-1]
		
	if dire[-1] == "/" and len(sys.argv) > 3: ## If directory allow multiple uplaods
		files = sys.argv[1:-1]
		for filename in files:
			dest = BASE_URL % dire.replace(BASE_URL_STR, "") + filename

			print "Transfering %s ..." % dest
			s =  wd.t3put(filename, BASE_URL % dire.replace(BASE_URL_STR, "") + filename, overwrite=True)
			if len(s) > 0:
			    print s
			
	else:
		s =  wd.t3put(sys.argv[1], BASE_URL % dire.replace(BASE_URL_STR, ""), overwrite=True)
		if len(s) > 0:
		    print s
		


if __name__ == "__main__":
	sys.exit(main())
