#!/usr/bin/env python
# encoding: utf-8
"""
untitled.py

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

from t3tools import T3Tools

import sys


help_message = '''
Delete files and folders on the storage system.

Author: Morten Dam Jørgensen, 2011

Examples:
 	> t3rm /user/username/myfolder
	> t3rm /user/usernanme/myfile.root

'''

def main(argv=None):
	dire = ""	

	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return

	wd = T3Tools()			
	for i in sys.argv[1:]:
		if i[0] == "/":
			dire = i
		else:
			dire = "/" + i
		s = wd.t3rm(dire)
        if len(s) > 0:
            print s


if __name__ == "__main__":
	sys.exit(main())
