#!/usr/bin/env python
# encoding: utf-8
"""
untitled.py

Created by Morten Dam Jørgensen on 2011-03-03.
Copyright (c) 2011 Niels Bohr Institute. All rights reserved.
"""

BASE_URL = "https://ftp1.ndgf.org:2881/atlas/disk/atlaslocalgroupdisk/dk%s"
BASE_URL_STR = "https://ftp1.ndgf.org:2881/atlas/disk/atlaslocalgroupdisk/dk"

import sys
import getopt
import os
import shlex, subprocess
from getpass import getpass

help_message = '''
Delete files and folders on the storage system.

Author: Morten Dam Jørgensen, 2011

Examples:
 	> t3rm /user/username/myfolder
	> t3rm /user/usernanme/myfile.root

'''



class NBIWebDAV(object):
	"""Communication with the Tier 3 storage element via WebDAV"""
	def __init__(self, pw=""):
		super(NBIWebDAV, self).__init__()
		self.homedir = os.path.expanduser('~')
		try:
		    pw_file = open("%s/.globus/t3password" % self.homedir, "r")
		    self.pw = pw_file.read()
		    pw_file.close()
		except:
		    try:
		        if open("%s/.globus/userkey.pem" % self.homedir, "r").read().find("ENCRYPTED") == -1:
		            self.pw = ""
		        else:
		            self.pw = getpass("Enter GRID password: ")
		            
		    except:
		        self.pw = getpass("Enter GRID password: ")


		
		
	def delete(self, path):
		"""docstring for delete"""
		exe = 'curl -ks --cert %s/.globus/usercert.pem:%s --key %s/.globus/userkey.pem --request DELETE %s' %(self.homedir, self.pw, self.homedir, path)
		a = subprocess.Popen(shlex.split(exe), stdout=subprocess.PIPE, stdin=subprocess.PIPE)
		return a.communicate()[0]
		


class Usage(Exception):
	def __init__(self, msg):
		self.msg = msg


def main(argv=None):
	dire = ""	

	if len(sys.argv) < 2 or "-h" in sys.argv:
		print help_message
		return

	wd = NBIWebDAV()			
	for i in sys.argv[1:]:
		if i[0] == "/":
			dire = i
		else:
			dire = "/" + i
		print wd.delete(BASE_URL % dire.replace(BASE_URL_STR, ""))



if __name__ == "__main__":
	sys.exit(main())
